version: '3'

services:
  redis:
    image: redis
    restart: always
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - '8000:8000'
  celery:
    build: .
    command: celery -A core worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis